on:
  push:
    paths:
      - '*'
      - '!.*'
      - '!*.md'
      - '!*.yml'
    branches:    
      - master
name: Build PDF
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build
      uses: docker://miktex/miktex:latest
      with:
        entrypoint: sh
        args: -c "echo \"\$pdflatex = 'pdflatex -interaction=nonstopmode';\" > ~/.latexmkrc && latexmk -f -pdf; pdflatex -jobname=draft main.tex"
    - name: Release
      uses: docker://python:3-buster
      with:
        entrypoint: sh
        args: -c "pip install github3.py && python .github/upload_release.py"
      env:
        ASSET_PATH: draft.pdf
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
